### ISSUE TITLE
Target list

### ISSUE THREAD

**Issue by 409H** [MrLuit/MyEtherWalletWhitehat#5]
Hey, if you're needing targets, go to http://eal-phishing-stats.herokuapp.com/ and you'll see all the domains caught with the last hit by EAL - everything is fetched from Google Analytics.

This involves domains that are similar to MyEtherWallet.com btw - there _could_ be some false positives, so make sure to check before you spam.

Hopefully this helps build a database for you guys :)

**Comment by MrLuit** [comment]
Thanks. Will check all of them today.

**Comment by MrLuit** [comment]
Added in 9a673bfbb54876b04e43b0630ef0c0b25d5f3757 :) Thanks!
